const STORAGE_KEY = 'job-match-mvp-v2';
const defaultProfile = {roles:'プロダクトマネージャー, Webディレクター',industries:'SaaS, IT',minSalary:500,maxCommute:150,employmentTypes:'正社員',excluded:'',skills:'プロジェクトマネジメント, 要件定義, SQL, UX, アジャイル'};
const defaultWeights = {skill:25,salary:20,content:20,workstyle:15,growth:10,stability:10};
const weightLabels = {skill:'スキル適合',salary:'給与',content:'仕事内容',workstyle:'働き方',growth:'成長性',stability:'企業安定性'};
const demoJobs = [
  {id:'demo-1',company:'Blue Harbor株式会社',title:'プロダクトマネージャー',location:'東京都品川区',station:'品川駅',salaryMin:650,salaryMax:900,employment:'正社員',remote:'ハイブリッド',description:'SaaSプロダクトのロードマップ策定、顧客課題の整理、要件定義、開発チームとのアジャイルな協働を担当。プロダクトマネジメント経験、SQLやデータ分析の経験を歓迎。転勤なし。',url:'https://example.com/jobs/blue-harbor',createdAt:'2026-08-02',commuteMinutes:78},
  {id:'demo-2',company:'湘南テック合同会社',title:'Webディレクター / UXリード',location:'神奈川県藤沢市',station:'藤沢駅',salaryMin:520,salaryMax:720,employment:'正社員',remote:'ハイブリッド',description:'Webサービスの企画、要件定義、UX改善、制作進行。ユーザーインタビューとデータをもとにプロダクトを改善します。湘南エリア勤務、転勤なし。',url:'https://example.com/jobs/shonan-tech',createdAt:'2026-08-01',commuteMinutes:35},
  {id:'demo-3',company:'North Star Labs',title:'事業開発マネージャー',location:'東京都千代田区',station:'東京駅',salaryMin:700,salaryMax:1100,employment:'正社員',remote:'出社',description:'新規事業の立ち上げと事業計画、アライアンス、チームマネジメント。高い成長環境。全国転勤の可能性があります。',url:'https://example.com/jobs/north-star',createdAt:'2026-07-31',commuteMinutes:92}
];

function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved||{profile:defaultProfile,weights:defaultWeights,jobs:demoJobs.map(j=>({...j,state:'new'}))}}catch{return{profile:defaultProfile,weights:defaultWeights,jobs:demoJobs.map(j=>({...j,state:'new'}))}}}
let state=loadState();
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const tokens=s=>String(s||'').toLowerCase().split(/[\s,、・/／|]+/).map(x=>x.trim()).filter(Boolean);
const hasAny=(text,words)=>tokens(words).some(w=>String(text||'').toLowerCase().includes(w));
const toList=s=>String(s||'').split(/[,、\n]/).map(x=>x.trim()).filter(Boolean);
function scoreJob(job){
  const p=state.profile,w=state.weights,text=`${job.title} ${job.description} ${job.location} ${job.remote}`.toLowerCase();
  const reasons=[],negative=[];let excluded=false;
  const excludedWords=toList(p.excluded); const excludedHit=excludedWords.some(w=>{const needle=w.toLowerCase();if(needle==='転勤')return /転勤(?!なし|無し)/.test(text);if(needle==='残業')return /残業(?!なし|無し|少な)/.test(text);return text.includes(needle)}); if(excludedHit){excluded=true;negative.push('除外キーワードに一致');}
  if(job.commuteMinutes!=null&&Number(job.commuteMinutes)>Number(p.maxCommute)){excluded=true;negative.push(`通勤${job.commuteMinutes}分で上限${p.maxCommute}分を超過`)}
  const skills=toList(p.skills);const matched=skills.filter(s=>text.includes(s.toLowerCase()));const skill=Math.min(100,Math.round((matched.length/Math.max(skills.length,1))*100));
  if(matched.length)reasons.push(`スキル一致：${matched.slice(0,3).join('、')}`);else negative.push('登録スキルとの一致が少ない');
  const salary=job.salaryMax>=p.minSalary?Math.min(100,Math.round((job.salaryMax/Math.max(p.minSalary,1))*70+30)):20;if(salary>=70)reasons.push(`年収${job.salaryMin}〜${job.salaryMax}万円`);else negative.push('希望最低年収を下回る可能性');
  const roles=toList(p.roles);const content=roles.some(r=>text.includes(r.toLowerCase()))?95:roles.some(r=>text.includes(r.toLowerCase().split(/[ /]/)[0]))?70:45;if(content>=70)reasons.push('希望職種との一致度が高い');
  const workstyle=job.remote==='フルリモート'?100:job.remote==='ハイブリッド'?78:job.remote==='出社'?42:55;if(workstyle>=75)reasons.push(`${job.remote}の働き方`);
  const growth=hasAny(text,'成長,新規事業,裁量,アジャイル,プロダクト')?82:55;const stability=hasAny(text,'上場,安定,大手,長期')?85:60;
  if(job.commuteMinutes==null)negative.push('通勤時間は要確認');
  const total=Math.round((skill*w.skill+salary*w.salary+content*w.content+workstyle*w.workstyle+growth*w.growth+stability*w.stability)/100);
  const completeness=[job.company,job.title,job.location,job.description,job.salaryMax,job.remote].filter(Boolean).length/6;const confidence=Math.round((completeness*70+(job.commuteMinutes!=null?30:0)));
  return{...job,total,confidence,excluded,reasons:reasons.slice(0,4),negative:negative.slice(0,4)};
}
function render(){const scored=state.jobs.map(scoreJob);const sort=document.querySelector('#sortJobs')?.value||'score';const list=[...scored].sort((a,b)=>sort==='newest'?String(b.createdAt).localeCompare(a.createdAt):sort==='salary'?b.salaryMax-a.salaryMax:b.total-a.total);const eligible=scored.filter(j=>!j.excluded);document.querySelector('#jobCount').textContent=scored.length;document.querySelector('#recommendedCount').textContent=eligible.filter(j=>j.total>=70).length;document.querySelector('#reviewCount').textContent=eligible.filter(j=>j.confidence<80).length;document.querySelector('#savedCount').textContent=scored.filter(j=>j.state==='saved').length;document.querySelector('#topScore').textContent=eligible.length?Math.max(...eligible.map(j=>j.total)):'—';document.querySelector('#jobList').innerHTML=list.length?list.map(jobCard).join(''):`<div class="card empty">まだ求人がありません。求人を追加して採点してみよう。</div>`;bindJobActions();}
function jobCard(j){const status=j.excluded?'<span class="pill red">対象外</span>':j.confidence<80?'<span class="pill">要確認</span>':'<span class="pill green">評価確度 高</span>';const commuteLink=j.station||j.location?`<a class="ghost-button" href="https://www.google.com/maps/dir/?api=1&origin=%E8%8C%85%E3%83%B6%E5%B4%8E%E9%A7%85&destination=${encodeURIComponent(j.station||j.location)}&travelmode=transit" target="_blank" rel="noreferrer">経路確認</a>`:'';return`<article class="job-card card"><div class="job-main"><div><p class="eyebrow">${esc(j.company)}</p><h3>${esc(j.title)}</h3><p class="job-meta">${esc(j.location)}${j.station?` / ${esc(j.station)}`:''} ・ ${j.employment} ・ ${j.remote}</p></div><div class="score-badge"><span>${j.excluded?'—':j.total}</span><small>${j.excluded?'対象外':'MATCH'}</small></div></div><div class="pills">${status}<span class="pill">年収 ${j.salaryMin||'?'}〜${j.salaryMax||'?'}万円</span>${j.commuteMinutes!=null?`<span class="pill">茅ヶ崎駅から${j.commuteMinutes}分</span>`:'<span class="pill red">通勤要確認</span>'}</div><div class="reasons">${j.reasons.map(x=>`<div class="reason">${esc(x)}</div>`).join('')}${j.negative.map(x=>`<div class="reason negative">${esc(x)}</div>`).join('')}</div><div class="job-actions"><button class="secondary-button" data-state="saved" data-id="${j.id}" type="button">${j.state==='saved'?'保存済み':'保存'}</button><button class="secondary-button" data-state="applied" data-id="${j.id}" type="button">${j.state==='applied'?'応募済み':'応募管理'}</button><button class="secondary-button" data-commute="${j.id}" type="button">${j.commuteMinutes!=null?'通勤を修正':'通勤を確認'}</button><button class="ghost-button danger-button" data-state="excluded" data-id="${j.id}" type="button">除外</button>${commuteLink}${j.url?`<a class="ghost-button" href="${esc(j.url)}" target="_blank" rel="noreferrer">原文</a>`:''}</div></article>`}
function bindJobActions(){document.querySelectorAll('[data-state]').forEach(b=>b.addEventListener('click',()=>{const job=state.jobs.find(j=>j.id===b.dataset.id);if(!job)return;job.state=job.state===b.dataset.state?'new':b.dataset.state;save();render();toast(job.state==='new'?'状態を戻しました':`「${b.dataset.state==='saved'?'保存':b.dataset.state==='applied'?'応募済み':'除外'}」にしました`)}));document.querySelectorAll('[data-commute]').forEach(b=>b.addEventListener('click',()=>{const job=state.jobs.find(j=>j.id===b.dataset.commute);if(!job)return;const answer=prompt(`茅ヶ崎駅から${job.station||job.location}までの片道時間（分）を入力してください。\n経路検索で確認した値を入力します。`,job.commuteMinutes??'');if(answer===null)return;const minutes=Number(answer);if(!Number.isFinite(minutes)||minutes<0){toast('0以上の分数を入力してください');return}job.commuteMinutes=minutes;save();render();toast(minutes>state.profile.maxCommute?'上限超過として対象外にしました':'通勤時間を保存しました')}))}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showProfile(){const f=document.querySelector('#profileForm');Object.entries(state.profile).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v})}
function showWeights(){const box=document.querySelector('#weightFields');box.innerHTML=Object.entries(weightLabels).map(([key,label])=>`<label class="weight-row"><span>${label}</span><input type="range" min="0" max="50" step="5" name="${key}" value="${state.weights[key]}"><output>${state.weights[key]}%</output></label>`).join('');box.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{i.nextElementSibling.value=`${i.value}%`;document.querySelector('#weightTotal').textContent=`${[...box.querySelectorAll('input')].reduce((a,x)=>a+Number(x.value),0)}%`;}));document.querySelector('#weightTotal').textContent=`${Object.values(state.weights).reduce((a,b)=>a+b,0)}%`}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector(`#${btn.dataset.tab}`).classList.add('active')}));
document.querySelector('#sortJobs').addEventListener('change',render);
document.querySelector('#jobForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));state.jobs.unshift({id:`job-${Date.now()}`,company:d.company,title:d.title,location:d.location,station:d.station,salaryMin:Number(d.salaryMin)||0,salaryMax:Number(d.salaryMax)||Number(d.salaryMin)||0,employment:d.employment,remote:d.remote,url:d.url,description:d.description,createdAt:new Date().toISOString().slice(0,10),state:'new'});save();e.currentTarget.reset();render();document.querySelector('[data-tab="jobs"]').click();toast('求人を採点して登録しました')});
document.querySelector('#profileForm').addEventListener('submit',e=>{e.preventDefault();state.profile=Object.fromEntries(new FormData(e.currentTarget));state.profile.minSalary=Number(state.profile.minSalary)||0;state.profile.maxCommute=Number(state.profile.maxCommute)||150;save();render();document.querySelector('#profileSaved').textContent='保存しました';setTimeout(()=>document.querySelector('#profileSaved').textContent='',2200);toast('プロフィールを保存して再採点しました')});
document.querySelector('#weightsForm').addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const total=Object.values(values).reduce((a,b)=>a+Number(b),0);if(total!==100){toast(`合計を100%にしてください（現在${total}%）`);return}state.weights=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,Number(v)]));save();render();toast('評価の重みを保存しました')});
document.querySelector('#resumeFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const profile=document.querySelector('#profileForm');const current=profile.elements.skills.value;const extracted=text.replace(/\s+/g,' ').slice(0,3000);profile.elements.skills.value=[current,extracted].filter(Boolean).join(', ');document.querySelector('#fileStatus').textContent=`${file.name}を端末内で読み込みました。内容を確認してプロフィールを保存してください。`;toast('ファイルを端末内で読み込みました')});
document.querySelector('#exportData').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({profile:state.profile,weights:state.weights,jobs:state.jobs},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`job-match-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);toast('バックアップを書き出しました')});
document.querySelector('#importData').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!Array.isArray(imported.jobs)||!imported.profile||!imported.weights)throw new Error('invalid');state={profile:imported.profile,weights:imported.weights,jobs:imported.jobs};save();showProfile();showWeights();render();toast('バックアップを復元しました')}catch{toast('このJSONはJob Matchのバックアップではありません')}});
document.querySelector('#resetDemo').addEventListener('click',()=>{if(confirm('デモデータを初期状態へ戻しますか？')){localStorage.removeItem(STORAGE_KEY);state=loadState();showProfile();showWeights();render();toast('デモをリセットしました')}});
showProfile();showWeights();render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
