import webpush from 'web-push';

const json = (value, status = 200, extra = {}) => new Response(JSON.stringify(value), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer', ...extra } });
const blankState = () => ({ version: 1, profile: null, weights: null, jobs: [], sources: [{ id: 'manual', name: '手動取込', mode: 'manual_only', approved: true, enabled: true, termsUrl: '', robotsUrl: '', minimumIntervalMinutes: 0 }], notifications: { morningEnabled: true, morningHour: 7, instantEnabled: true, threshold: 80, minimumConfidence: 80 }, subscriptions: [], notificationLog: [], meta: { createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), lastMorningDate: null, vapid: null } });
const publicState = state => { const { subscriptions, ...safe } = state; return safe; };
const cookies = request => Object.fromEntries((request.headers.get('Cookie') || '').split(';').map(item => item.trim().split('=').map(decodeURIComponent)).filter(pair => pair.length === 2));
const utf8 = value => new TextEncoder().encode(value);
const b64 = bytes => btoa(String.fromCharCode(...bytes)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
const unb64 = value => Uint8Array.from(atob(value.replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(value.length / 4) * 4, '=')), c => c.charCodeAt(0));
const hmac = async (secret, value) => new Uint8Array(await crypto.subtle.sign('HMAC', await crypto.subtle.importKey('raw', utf8(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']), utf8(value)));
const same = (a, b) => a.length === b.length && a.reduce((result, value, index) => result | (value ^ b[index]), 0) === 0;
async function sessionIsValid(request, env) { if (!env.APP_PASSWORD) return true; const [payload, signature] = (cookies(request).job_match_session || '').split('.'); if (!payload || !signature || !same(await hmac(env.SESSION_SECRET, payload), unb64(signature))) return false; try { return JSON.parse(new TextDecoder().decode(unb64(payload))).exp > Date.now(); } catch { return false; } }
async function createSession(env) { const payload = b64(utf8(JSON.stringify({ exp: Date.now() + 30 * 24 * 60 * 60_000, nonce: crypto.randomUUID() }))); return `${payload}.${b64(await hmac(env.SESSION_SECRET, payload))}`; }
async function passwordMatches(value, env) { return same(await hmac(env.SESSION_SECRET, String(value || '')), await hmac(env.SESSION_SECRET, env.APP_PASSWORD || '')); }
async function readState(env) { const row = await env.DB.prepare('SELECT state FROM app_state WHERE id = 1').first(); try { return row ? { ...blankState(), ...JSON.parse(row.state) } : blankState(); } catch { return blankState(); } }
async function writeState(env, state) { state.meta = { ...state.meta, updatedAt: new Date().toISOString() }; await env.DB.prepare('INSERT INTO app_state (id, state, updated_at) VALUES (1, ?, ?) ON CONFLICT(id) DO UPDATE SET state = excluded.state, updated_at = excluded.updated_at').bind(JSON.stringify(state), state.meta.updatedAt).run(); }
async function ensureVapid(env, state) { if (!state.meta.vapid?.publicKey) { state.meta.vapid = webpush.generateVAPIDKeys(); await writeState(env, state); } webpush.setVapidDetails(env.VAPID_SUBJECT || 'mailto:admin@example.invalid', state.meta.vapid.publicKey, state.meta.vapid.privateKey); return state.meta.vapid.publicKey; }
async function sendPush(env, state, payload) { await ensureVapid(env, state); const kept = []; for (const subscription of state.subscriptions || []) { try { await webpush.sendNotification(subscription, JSON.stringify(payload)); kept.push(subscription); } catch (error) { if (![404, 410].includes(error.statusCode)) kept.push(subscription); } } state.subscriptions = kept; state.notificationLog = [...(state.notificationLog || []), { id: crypto.randomUUID(), type: payload.type, createdAt: new Date().toISOString() }].slice(-300); await writeState(env, state); }
const entity = value => value.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"');
const tag = (xml, name) => { const match = new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`, 'i').exec(xml); return match ? entity(match[1].replace(/<[^>]+>/g, '').trim()) : ''; };
const entries = xml => (xml.match(/<(item|entry)(?:\s[^>]*)?>[\s\S]*?<\/\1>/gi) || []).map(block => ({ title: tag(block, 'title'), url: tag(block, 'link') || (/<link[^>]+href=["']([^"']+)/i.exec(block)?.[1] || ''), description: tag(block, 'description') || tag(block, 'summary') || tag(block, 'content') }));
async function collectFeeds(env, state) { let changed = false; for (const source of state.sources || []) { if (source.mode !== 'feed' || !source.approved || !source.enabled || !source.url || !source.termsUrl || !source.robotsUrl) continue; let url; try { url = new URL(source.url); } catch { continue; } if (url.protocol !== 'https:' || /^localhost$/i.test(url.hostname) || /^127\./.test(url.hostname)) continue; const interval = Math.max(60, Number(source.minimumIntervalMinutes) || 60) * 60_000; if (Date.now() - (Date.parse(source.lastCollectedAt || 0) || 0) < interval) continue; source.lastCollectedAt = new Date().toISOString(); changed = true; try { const response = await fetch(url, { redirect: 'error', headers: { 'User-Agent': 'JobMatch/1.0 (compliance-managed feed collector)' } }); if (!response.ok) continue; for (const item of entries(await response.text())) { if (!item.title || !item.url || state.jobs.some(job => job.url === item.url)) continue; state.jobs.push({ id: crypto.randomUUID(), sourceKey: `${source.id}|${item.url}`.toLowerCase().replace(/\s+/g, ''), company: source.name, title: item.title, location: '要確認', station: '', salaryMin: 0, salaryMax: 0, employment: '不明', remote: '不明', url: item.url, description: item.description, createdAt: new Date().toISOString(), state: 'new', importedFrom: source.id, confidence: 30, total: 0 }); } } catch {} } if (changed) await writeState(env, state); }
async function scheduled(env) { const state = await readState(env); await collectFeeds(env, state); const now = new Date(); const date = now.toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' }); const hour = Number(new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', hour: '2-digit', hour12: false }).format(now)); if (state.notifications?.morningEnabled && hour === Number(state.notifications.morningHour) && state.meta.lastMorningDate !== date) { const jobs = state.jobs.filter(job => !job.excluded).sort((a, b) => (b.total || 0) - (a.total || 0)).slice(0, 3); if (jobs.length) await sendPush(env, state, { type: 'morning', title: 'Job Match: 今日のおすすめ', body: jobs.map(job => `${job.total}点 ${job.title}`).join('\n'), url: '/' }); state.meta.lastMorningDate = date; await writeState(env, state); } }

export default { async fetch(request, env) { const path = new URL(request.url).pathname; if (path === '/healthz') return json({ ok: true, version: 1 }); if (!path.startsWith('/api/')) return env.ASSETS.fetch(request); if (path === '/api/auth/status') return json({ required: Boolean(env.APP_PASSWORD), authenticated: await sessionIsValid(request, env) }); if (path === '/api/auth/login' && request.method === 'POST') { const payload = await request.json().catch(() => ({})); if (!env.APP_PASSWORD || await passwordMatches(payload.password, env)) return json({ ok: true }, 200, { 'Set-Cookie': `job_match_session=${await createSession(env)}; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=2592000` }); return json({ error: 'Invalid password' }, 401); } if (path === '/api/auth/logout' && request.method === 'POST') return new Response(null, { status: 204, headers: { 'Set-Cookie': 'job_match_session=; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=0' } }); if (!(await sessionIsValid(request, env))) return json({ error: 'Authentication required' }, 401); const state = await readState(env); if (path === '/api/state' && request.method === 'GET') return json(publicState(state)); if (path === '/api/state' && request.method === 'PUT') { const incoming = await request.json(); const next = { ...state, profile: incoming.profile || null, weights: incoming.weights || null, jobs: Array.isArray(incoming.jobs) ? incoming.jobs.slice(0, 2000) : state.jobs, notifications: incoming.notifications || state.notifications, sources: Array.isArray(incoming.sources) ? incoming.sources : state.sources }; await writeState(env, next); return json(publicState(next)); } if (path === '/api/export' && request.method === 'GET') return json(publicState(state)); if (path === '/api/push/key' && request.method === 'GET') return json({ publicKey: await ensureVapid(env, state) }); if (path === '/api/push/subscribe' && request.method === 'POST') { const subscription = await request.json(); if (!subscription?.endpoint || !subscription?.keys?.p256dh || !subscription?.keys?.auth) return json({ error: 'Invalid subscription' }, 400); state.subscriptions = [...state.subscriptions.filter(item => item.endpoint !== subscription.endpoint), subscription]; await writeState(env, state); return json({ ok: true }, 201); } if (path === '/api/push/test' && request.method === 'POST') { await sendPush(env, state, { type: 'test', title: 'Job Match', body: '通知の設定が完了しました。', url: '/' }); return json({ ok: true }); } if (path === '/api/push/job' && request.method === 'POST') { const payload = await request.json(); await sendPush(env, state, { type: 'job', title: payload.title || '高得点の新着求人', body: payload.body || '', url: '/' }); return json({ ok: true }); } if (path === '/api/sources/collect' && request.method === 'POST') { await collectFeeds(env, state); return json(publicState(await readState(env))); } return json({ error: 'Not found' }, 404); }, async scheduled(_, env, ctx) { ctx.waitUntil(scheduled(env)); } };
